"""Debug export utilities: OBJ writing, mesh stats, and numeric comparison."""

from pathlib import Path

import numpy as np


def export_obj(vertices: np.ndarray, indices: np.ndarray, path) -> None:
    """Write a standard Wavefront OBJ from vertex and index arrays.

    vertices: (N, 8) float32 — x,y,z,nx,ny,nz,u,v
    indices:  (M,)  uint16  — triangle list (M must be divisible by 3)
    """
    path = Path(path)
    lines = ["# Generated by ko2mc debug_export"]

    for v in vertices:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    for v in vertices:
        lines.append(f"vn {v[3]:.6f} {v[4]:.6f} {v[5]:.6f}")
    for v in vertices:
        lines.append(f"vt {v[6]:.6f} {v[7]:.6f}")

    n_faces = len(indices) // 3
    for i in range(n_faces):
        a, b, c = int(indices[i * 3]), int(indices[i * 3 + 1]), int(indices[i * 3 + 2])
        # OBJ is 1-indexed; shared v/vt/vn index per vertex
        lines.append(f"f {a+1}/{a+1}/{a+1} {b+1}/{b+1}/{b+1} {c+1}/{c+1}/{c+1}")

    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def print_mesh_stats(mesh) -> None:
    """Print summary statistics for an N3PMesh to stdout."""
    n_verts = len(mesh.vertices)
    n_faces = len(mesh.indices) // 3

    if n_verts > 0:
        pos = mesh.vertices[:, :3]
        bbox_min = pos.min(axis=0)
        bbox_max = pos.max(axis=0)
        center = (bbox_min + bbox_max) / 2.0
        radius = float(np.linalg.norm(pos - center, axis=1).max())
    else:
        bbox_min = bbox_max = np.zeros(3)
        radius = 0.0

    print(f"Mesh: '{mesh.name}'")
    print(f"  Vertices: {n_verts}  Faces: {n_faces}")
    print(
        f"  BBox min: ({bbox_min[0]:.3f}, {bbox_min[1]:.3f}, {bbox_min[2]:.3f})"
    )
    print(
        f"  BBox max: ({bbox_max[0]:.3f}, {bbox_max[1]:.3f}, {bbox_max[2]:.3f})"
    )
    print(f"  Radius:   {radius:.3f}")
    print(
        f"  LOD range: verts {mesh.min_vertices}–{mesh.max_vertices}, "
        f"idx {mesh.min_indices}–{mesh.max_indices}"
    )


def mesh_summary_json(mesh) -> dict:
    """Return mesh summary as a JSON-serializable dict (for golden regression output)."""
    n_verts = len(mesh.vertices)
    n_faces = len(mesh.indices) // 3

    if n_verts > 0:
        pos = mesh.vertices[:, :3]
        bbox_min = pos.min(axis=0).tolist()
        bbox_max = pos.max(axis=0).tolist()
        center = (pos.min(axis=0) + pos.max(axis=0)) / 2.0
        radius = float(np.linalg.norm(pos - center, axis=1).max())
    else:
        bbox_min = bbox_max = [0.0, 0.0, 0.0]
        radius = 0.0

    return {
        "name": mesh.name,
        "vertex_count": n_verts,
        "face_count": n_faces,
        "bbox_min": bbox_min,
        "bbox_max": bbox_max,
        "radius": radius,
        "lod": {
            "min_vertices": mesh.min_vertices,
            "max_vertices": mesh.max_vertices,
            "min_indices": mesh.min_indices,
            "max_indices": mesh.max_indices,
        },
    }


def compare_obj(generated_path, reference_path, epsilon: float = 1e-4) -> bool:
    """Numerically compare two OBJ files within epsilon tolerance.

    Compares: vertex counts, face counts, per-vertex positions/normals/UVs,
    and per-face vertex indices.

    Returns True if they match, prints diffs and returns False otherwise.
    """

    def _parse_obj(path):
        verts, normals, uvs, faces = [], [], [], []
        for line in Path(path).read_text(encoding="ascii", errors="replace").splitlines():
            parts = line.split()
            if not parts:
                continue
            tag = parts[0]
            if tag == "v":
                verts.append([float(x) for x in parts[1:4]])
            elif tag == "vn":
                normals.append([float(x) for x in parts[1:4]])
            elif tag == "vt":
                uvs.append([float(x) for x in parts[1:3]])
            elif tag == "f":
                face = [int(tok.split("/")[0]) - 1 for tok in parts[1:]]
                faces.append(face)
        return (
            np.array(verts, dtype=np.float32) if verts else np.zeros((0, 3), dtype=np.float32),
            np.array(normals, dtype=np.float32) if normals else np.zeros((0, 3), dtype=np.float32),
            np.array(uvs, dtype=np.float32) if uvs else np.zeros((0, 2), dtype=np.float32),
            faces,
        )

    g_v, g_vn, g_vt, g_f = _parse_obj(generated_path)
    r_v, r_vn, r_vt, r_f = _parse_obj(reference_path)

    ok = True

    if len(g_v) != len(r_v):
        print(f"  MISMATCH vertex count: got {len(g_v)}, expected {len(r_v)}")
        ok = False
    if len(g_f) != len(r_f):
        print(f"  MISMATCH face count: got {len(g_f)}, expected {len(r_f)}")
        ok = False

    if len(g_v) == len(r_v) and len(g_v) > 0:
        max_pos_err = float(np.abs(g_v - r_v).max())
        if max_pos_err > epsilon:
            print(f"  MISMATCH positions: max error {max_pos_err:.6f} > epsilon {epsilon}")
            ok = False
        else:
            print(f"  OK positions: max error {max_pos_err:.6f}")

    if len(g_vn) == len(r_vn) and len(g_vn) > 0:
        max_n_err = float(np.abs(g_vn - r_vn).max())
        if max_n_err > epsilon:
            print(f"  MISMATCH normals: max error {max_n_err:.6f} > epsilon {epsilon}")
            ok = False
        else:
            print(f"  OK normals: max error {max_n_err:.6f}")

    if len(g_vt) == len(r_vt) and len(g_vt) > 0:
        max_uv_err = float(np.abs(g_vt - r_vt).max())
        if max_uv_err > epsilon:
            print(f"  MISMATCH UVs: max error {max_uv_err:.6f} > epsilon {epsilon}")
            ok = False
        else:
            print(f"  OK UVs: max error {max_uv_err:.6f}")

    if len(g_f) == len(r_f):
        mismatches = sum(1 for gf, rf in zip(g_f, r_f) if gf != rf)
        if mismatches:
            print(f"  MISMATCH faces: {mismatches}/{len(g_f)} faces differ")
            ok = False
        else:
            print(f"  OK faces: {len(g_f)} faces match")

    return ok
